function Irow = inertia_row_3(rob,in2)
%% INERTIA_ROW_3 - Computation of the robot specific inertia matrix row for corresponding to joint 3 of 7. 
% ========================================================================= 
%    
%    Irow = inertia_row_3(rob,q) 
%    Irow = rob.inertia_row_3(q) 
%    
%  Description:: 
%    Given a full set of joint variables this function computes the 
%    inertia matrix row number 3 of 7 for PANDA. 
%    
%  Input:: 
%    rob: robot object of PANDA specific class 
%    q:  7-element vector of generalized 
%         coordinates 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    Irow:  [1x7] row of the robot inertia matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also coriolis.
%    
    
% Copyright (C) 1993-2023, by Peter I. Corke 
% Copyright (C) 2012-2023, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Dec-2023 10:10:15
sympref('FloatingPointOutput',true)
syms m6 m7
syms r6x r6y r6z
syms r7x r7y r7z

q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
q7 = in2(:,7);

t2 = cos(q3);
t3 = cos(q4);
t4 = cos(q5);
t5 = cos(q6);
t6 = cos(q7);
t7 = sin(q3);
t8 = sin(q4);
t9 = sin(q5);
t10 = sin(q6);
t11 = sin(q7);
t12 = t3.*t5;
t13 = t3.*t10;
t14 = r6x.*t8.*t9;
t15 = r6y.*t8.*t9;
t16 = t8.*t9.*t11;
t17 = t4.*t5.*t8;
t18 = t4.*t8.*t10;
t19 = t6.*t8.*t9;
t20 = t3.*(3.3e+1./4.0e+2);
t21 = t8.*(4.8e+1./1.25e+2);
t25 = t8.*t9.*(1.1e+1./1.25e+2);
t34 = t3.*1.183948e-1;
t40 = t8.*1.183948e-1;
t41 = t3.*4.54293e-2;
t42 = t3.*2.1633e-4;
t44 = t8.*2.333074e-1;
t45 = t4.*t8.*1.644108e-1;
t46 = t8.*t9.*1.644108e-1;
t50 = t4.*t8.*4.54293e-2;
t51 = t8.*t9.*2.1633e-4;
t52 = t8.*1.92478605e-2;
t54 = t4.*t8.*3.74791725e-3;
t55 = t8.*t9.*1.7847225e-5;
t76 = t8.*1.120888863e-6;
t81 = t3.*2.62507583e-7;
t82 = t8.*2.62507583e-7;
t87 = t8.*t9.*1.2066987492e-5;
t92 = t8.*t9.*7.2256604e-8;
t107 = t8.*2.5709069623697e-2;
t109 = t3.*1.632660816059e-3;
t112 = t3.*9.240993901422e-3;
t115 = t8.*t9.*1.632660816059e-3;
t116 = t4.*t8.*1.9224763077146e-2;
t117 = t3.*1.3150721918838e-2;
t124 = t8.*t9.*1.997723604999e-2;
t125 = t3.*1.5658737968e-5;
t132 = t4.*t8.*1.5658737968e-5;
t134 = t4.*t8.*4.991057278e-6;
t135 = t8.*t9.*4.991057278e-6;
t22 = -t18;
t24 = t12.*(1.1e+1./1.25e+2);
t27 = t13+t17;
t28 = t18.*(1.1e+1./1.25e+2);
t43 = -t40;
t49 = -t42;
t59 = t20+t21-3.3e+1./4.0e+2;
t74 = t12.*2.417464660303e-3;
t75 = t13.*1.88230244108e-3;
t79 = t18.*2.417464660303e-3;
t80 = t17.*1.88230244108e-3;
t85 = t12.*1.2066987492e-5;
t88 = t19.*3.390625e-4;
t89 = t16.*3.390625e-4;
t90 = -t81;
t91 = -t82;
t95 = -t87;
t96 = t13.*7.2256604e-8;
t97 = -t92;
t98 = t18.*1.2066987492e-5;
t100 = t12.*3.150206e-9;
t101 = t13.*3.150206e-9;
t102 = t17.*7.2256604e-8;
t104 = t17.*3.150206e-9;
t105 = t18.*3.150206e-9;
t130 = -t125;
t137 = -t132;
t26 = -t24;
t29 = r6y.*t27;
t30 = r6z.*t27;
t31 = t12+t22;
t32 = t6.*t27;
t33 = t11.*t27;
t63 = t4.*t59;
t66 = t5.*t9.*t59;
t67 = t9.*t10.*t59;
t73 = t9.*t59.*2.1633;
t78 = t9.*t59.*1.644108e-1;
t84 = t9.*t59.*4.54293e-2;
t86 = -t79;
t94 = -t85;
t99 = -t96;
t103 = -t102;
t106 = -t105;
t35 = r6x.*t31;
t36 = r7x.*t31;
t37 = r7y.*t31;
t38 = r6z.*t31;
t39 = -t30;
t53 = t16+t32;
t64 = r7x.*(t19-t33);
t65 = r7z.*(t19-t33);
t68 = t6.*t66;
t69 = t11.*t66;
t72 = t63.*2.1633;
t77 = t63.*1.644108e-1;
t83 = t63.*2.1633e-4;
t108 = t33.*3.390625e-4;
t110 = t32.*3.390625e-4;
t114 = t26+t28+t63;
t47 = -t35;
t48 = -t38;
t57 = r7y.*t53;
t58 = r7z.*t53;
t70 = -t68;
t71 = -t69;
t93 = -t83;
t111 = -t108;
t113 = t14+t39+t67;
t122 = t6.*t114;
t123 = t11.*t114;
t61 = -t57;
t118 = t15+t48+t66;
t119 = m6.*t113;
t131 = -t122;
t138 = t29+t47+t63;
t150 = t37+t65+t70+t123;
t120 = r6x.*t119;
t121 = r6z.*t119;
t126 = m6.*t118;
t139 = m6.*t138;
t143 = t25+t61+t64+t67;
t149 = t36+t58+t71+t131;
t155 = m7.*r7y.*t150;
t156 = m7.*r7z.*t150;
t158 = m7.*t6.*t150;
t159 = m7.*t11.*t150;
t127 = r6y.*t126;
t128 = r6z.*t126;
t129 = -t121;
t133 = -t126;
t140 = r6x.*t139;
t141 = r6y.*t139;
t144 = m7.*t143;
t151 = m7.*r7x.*t149;
t152 = m7.*r7z.*t149;
t153 = m7.*t6.*t149;
t154 = m7.*t11.*t149;
t161 = t159.*(1.1e+1./1.25e+2);
t136 = -t128;
t142 = -t140;
t145 = r7x.*t144;
t146 = r7y.*t144;
t148 = t144.*(1.1e+1./1.25e+2);
t157 = -t153;
t160 = t153.*(1.1e+1./1.25e+2);
t162 = -t161;
t163 = t119+t144;
t171 = t133+t154+t158;
t147 = -t146;
t164 = t5.*t163;
t165 = t10.*t163;
t168 = t88+t111+t145+t156;
t175 = t5.*t171;
t176 = t10.*t171;
t179 = t45+t49+t72+t139+t157+t159;
t197 = t74+t86+t95+t101+t104+t136+t142+t151+t155+t160+t162;
t166 = t164.*(3.3e+1./4.0e+2);
t167 = t89+t110+t147+t152;
t172 = t6.*t168;
t173 = t11.*t168;
t177 = -t175;
t178 = t176.*(3.3e+1./4.0e+2);
t180 = t4.*t179;
t181 = t9.*t179;
t185 = t43+t50+t51+t164+t176;
t198 = t5.*t197;
t199 = t10.*t197;
t169 = t6.*t167;
t170 = t11.*t167;
t174 = -t173;
t182 = t180.*(4.8e+1./1.25e+2);
t183 = t180.*(3.3e+1./4.0e+2);
t184 = t181.*(4.8e+1./1.25e+2);
t186 = t8.*t185;
t188 = t3.*t185.*(-3.3e+1./4.0e+2);
t189 = t41+t46+t73+t165+t177;
t200 = -t199;
t190 = t4.*t189;
t191 = t9.*t189;
t201 = t75+t80+t97+t100+t106+t129+t141+t169+t174;
t210 = t78+t94+t98+t99+t103+t109+t120+t124+t127+t134+t148+t170+t172;
t192 = -t190;
t193 = t190.*(4.8e+1./1.25e+2);
t194 = t191.*(4.8e+1./1.25e+2);
t195 = t191.*(3.3e+1./4.0e+2);
t203 = t5.*t201;
t204 = t10.*t201;
t209 = t44+t180+t191-2.872815e-1;
t211 = t4.*t210;
t212 = t9.*t210;
t196 = -t193;
t202 = t34+t181+t192;
t213 = -t211;
t215 = t77+t116+t130+t135+t200+t203;
t218 = t84+t91+t93+t115+t117+t137+t183+t195+t198+t204;
t205 = t3.*t202;
t207 = t8.*t202.*(3.3e+1./4.0e+2);
t216 = t4.*t215;
t217 = t9.*t215;
t219 = t3.*t218;
t220 = t8.*t218;
t206 = -t205;
t208 = -t207;
t221 = -t220;
t222 = t90+t107+t182+t194+t212+t216-1.92478605e-2;
t214 = t186+t206+1.21686e-1;
t223 = t3.*t222;
t224 = t8.*t222;
t225 = t54+t55+t76+t112+t166+t178+t184+t188+t196+t208+t213+t217-1.7127722301422e-2;
t226 = t221+t223+1.120384479e-6;
mt1 = [-cos(q2).*(t52+t183+t195-t219-t224-2.9212833471327e-2)-sin(q2).*(t2.*t209.*(7.9e+1./2.5e+2)+t7.*t214.*(7.9e+1./2.5e+2)+t2.*t226-t7.*t225),t2.*t214.*(-7.9e+1./2.5e+2)+t7.*t209.*(7.9e+1./2.5e+2)+t2.*t225+t7.*t226,-t52-t183-t195+t219+t224+2.9212833471327e-2];
mt2 = [-t54-t55-t76-t112-t166-t178-t184+t193+t211-t217,t3.*3.13527046481e-3+t84+t93+t115+t137+t198+t204,t94+t98+t99+t103+t120+t127+t148+t170+t172+t8.*t9.*2.133520179065e-3];
mt3 = [t12.*(-5.281249999999999e-4)+t18.*5.281249999999999e-4-t151-t155];
Irow = [mt1,mt2,mt3];
end
