function Irow = inertia_row_4(rob,in2)
%% INERTIA_ROW_4 - Computation of the robot specific inertia matrix row for corresponding to joint 4 of 7. 
% ========================================================================= 
%    
%    Irow = inertia_row_4(rob,q) 
%    Irow = rob.inertia_row_4(q) 
%    
%  Description:: 
%    Given a full set of joint variables this function computes the 
%    inertia matrix row number 4 of 7 for PANDA. 
%    
%  Input:: 
%    rob: robot object of PANDA specific class 
%    q:  7-element vector of generalized 
%         coordinates 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    Irow:  [1x7] row of the robot inertia matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also coriolis.
%    
    
% Copyright (C) 1993-2023, by Peter I. Corke 
% Copyright (C) 2012-2023, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Dec-2023 10:10:18
sympref('FloatingPointOutput',true)
syms m6 m7
syms r6x r6y r6z
syms r7x r7y r7z

q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
q7 = in2(:,7);

t2 = cos(q3);
t3 = cos(q4);
t4 = cos(q5);
t5 = cos(q6);
t6 = cos(q7);
t7 = sin(q3);
t8 = sin(q4);
t9 = sin(q5);
t10 = sin(q6);
t11 = sin(q7);
t12 = r6x.*t4;
t13 = r6y.*t4;
t14 = t4.*t6;
t15 = t4.*t11;
t16 = r6y.*t5.*t9;
t17 = r6z.*t5.*t9;
t18 = r6x.*t9.*t10;
t19 = r7x.*t9.*t10;
t20 = r7y.*t9.*t10;
t21 = r6z.*t9.*t10;
t22 = t5.*t6.*t9;
t23 = t5.*t9.*t11;
t26 = t4.*(1.1e+1./1.25e+2);
t27 = t5.*(3.3e+1./4.0e+2);
t28 = t9.*(4.8e+1./1.25e+2);
t29 = t10.*(3.3e+1./4.0e+2);
t32 = t4.*t5.*(4.8e+1./1.25e+2);
t33 = t4.*t10.*(4.8e+1./1.25e+2);
t34 = t9.*t10.*(1.1e+1./1.25e+2);
t39 = t4.*9.95118e-1;
t40 = t9.*9.95118e-1;
t44 = t4.*2.1633e-4;
t45 = t9.*4.54293e-2;
t50 = t9.*3.74791725e-3;
t51 = t4.*1.7847225e-5;
t71 = t9.*t10.*2.417464660303e-3;
t72 = t5.*t9.*1.88230244108e-3;
t73 = t4.*1.2066987492e-5;
t76 = t4.*7.2256604e-8;
t79 = t9.*t10.*1.2066987492e-5;
t83 = t5.*t9.*7.2256604e-8;
t84 = t5.*t9.*3.150206e-9;
t85 = t9.*t10.*3.150206e-9;
t88 = t4.*1.9077512016059e-2;
t89 = t9.*8.2358510277146e-2;
t90 = t4.*8.311098324999e-2;
t91 = t9.*9.8729457968e-5;
t92 = t4.*4.991057278e-6;
t93 = t9.*4.991057278e-6;
t25 = -t21;
t30 = -t22;
t31 = -t27;
t35 = t14+t23;
t48 = t29+t32;
t49 = t28+t34;
t52 = t16+t18+t28;
t53 = -t51;
t74 = t14.*3.390625e-4;
t75 = t15.*3.390625e-4;
t77 = -t73;
t78 = t22.*3.390625e-4;
t80 = t23.*3.390625e-4;
t82 = -t79;
t86 = -t84;
t87 = -t85;
t94 = -t92;
t95 = -t93;
t36 = r7x.*t35;
t37 = r7z.*t35;
t38 = t15+t30;
t54 = t11.*t49;
t55 = m6.*t52;
t56 = t6.*t48;
t57 = t11.*t48;
t58 = t6.*t49;
t62 = t12+t17+t31+t33;
t63 = t13+t25+t48;
t81 = -t78;
t41 = r7y.*t38;
t42 = r7z.*t38;
t59 = r6x.*t55;
t60 = r6y.*t55;
t61 = -t57;
t64 = m6.*t62;
t67 = m6.*t63;
t105 = -m7.*r7y.*(t20+t37-t54-t56);
t111 = -m7.*t11.*(t20+t37-t54-t56);
t112 = m7.*r7y.*(t20+t37-t54-t56);
t113 = m7.*r7z.*(t20+t37-t54-t56);
t116 = m7.*t11.*(t20+t37-t54-t56).*(-1.1e+1./1.25e+2);
t46 = -t41;
t65 = r6x.*t64;
t66 = r6z.*t64;
t68 = r6y.*t67;
t69 = r6z.*t67;
t102 = t19+t42+t58+t61;
t70 = -t69;
t96 = t26+t31+t33+t36+t46;
t104 = m7.*r7x.*t102;
t106 = m7.*r7z.*t102;
t108 = m7.*t6.*t102;
t110 = m7.*t11.*t102;
t97 = m7.*t96;
t115 = t108.*(1.1e+1./1.25e+2);
t124 = t40+t55+t108+t111;
t125 = -t5.*(-t67+t110+m7.*t6.*(t20+t37-t54-t56));
t130 = t10.*(-t67+t110+m7.*t6.*(t20+t37-t54-t56)).*(-3.3e+1./4.0e+2);
t98 = r7x.*t97;
t99 = r7y.*t97;
t101 = t97.*(1.1e+1./1.25e+2);
t117 = t64+t97;
t127 = t9.*t124;
t128 = t4.*t124;
t131 = t28.*t124;
t153 = t59+t70+t71+t77+t86+t104+t112+t115+t116;
t100 = -t99;
t118 = t5.*t117;
t119 = t10.*t117;
t132 = t128.*(4.8e+1./1.25e+2);
t133 = t128.*(3.3e+1./4.0e+2);
t135 = t74+t80+t98+t113;
t154 = t5.*t153;
t155 = t10.*t153;
t122 = t118.*(-3.3e+1./4.0e+2);
t134 = -t133;
t136 = t75+t81+t100+t106;
t137 = t6.*t135;
t138 = t11.*t135;
t142 = t39+t119+t125;
t152 = t3.*(t44-t45+t118+t10.*(-t67+t110+m7.*t6.*(t20+t37-t54-t56))-1.7847225e-1).*(3.3e+1./4.0e+2);
t139 = t6.*t136;
t140 = t11.*t136;
t143 = t4.*t142;
t144 = t9.*t142;
t141 = -t139;
t145 = t143.*(4.8e+1./1.25e+2);
t147 = t144.*(3.3e+1./4.0e+2);
t148 = t144.*(-4.8e+1./1.25e+2);
t157 = t127+t143+2.333074e-1;
t166 = t65+t68+t82+t83+t90+t95+t101+t137+t140-1.7847225e-5;
t158 = t3.*t157;
t160 = t8.*t157.*(3.3e+1./4.0e+2);
t162 = t60+t66+t72+t76+t87+t138+t141;
t167 = t4.*t166;
t168 = t9.*t166;
t161 = -t160;
t163 = t5.*t162;
t164 = t10.*t162;
t169 = -t168;
t165 = -t164;
t171 = t89+t94+t155+t163+3.74791725e-3;
t172 = t4.*t171;
t173 = t9.*t171;
t174 = t88+t91+t134+t147+t154+t165-9.240993901422e-3;
t175 = t3.*t174;
t176 = t8.*t174;
t177 = t132+t148+t169+t172+1.120888863e-6;
t180 = t50+t53+t122+t130+t131+t145+t152+t161+t167+t173+3.2217086146327e-2;
t178 = t3.*t177;
t179 = t8.*t177;
t181 = t176+t178;
mt1 = [cos(q2).*(t133-t147+t175-t179)-sin(q2).*(t7.*(t158+t8.*(t44-t45+t118+t10.*(-t67+t110+m7.*t6.*(t20+t37-t54-t56))-1.7847225e-1)).*(7.9e+1./2.5e+2)-t2.*t181+t7.*t180-t2.*(t128-t144).*(7.9e+1./2.5e+2)),t2.*(t158+t8.*(t44-t45+t118+t10.*(-t67+t110+m7.*t6.*(t20+t37-t54-t56))-1.7847225e-1)).*(-7.9e+1./2.5e+2)-t2.*t180-t7.*t181-t7.*(t128-t144).*(7.9e+1./2.5e+2),t133-t147+t175-t179];
mt2 = [t50+t53+t122+t130+t131+t145+t167+t173+3.2217086146327e-2,t88+t91+t154+t165,t4.*2.133520179065e-3+t65+t68+t82+t83+t101+t137+t140,-t104+t105-t9.*t10.*5.281249999999999e-4];
Irow = [mt1,mt2];
end
