function Irow = inertia_row_1(rob,in2)
%% INERTIA_ROW_1 - Computation of the robot specific inertia matrix row for corresponding to joint 1 of 5. 
% ========================================================================= 
%    
%    Irow = inertia_row_1(rob,q) 
%    Irow = rob.inertia_row_1(q) 
%    
%  Description:: 
%    Given a full set of joint variables this function computes the 
%    inertia matrix row number 1 of 5 for PANDA_sym. 
%    
%  Input:: 
%    rob: robot object of PANDA_sym specific class 
%    q:  5-element vector of generalized 
%         coordinates 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    Irow:  [1x5] row of the robot inertia matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also coriolis.
%    
    
% Copyright (C) 1993-2023, by Peter I. Corke 
% Copyright (C) 2012-2023, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Dec-2023 16:12:34

sympref('FloatingPointOutput',true);
syms m4 m5
q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
t2 = cos(q2);
t3 = cos(q3);
t4 = q2+q3;
t5 = q2.*2.0;
t7 = cos(t5);
t8 = cos(t4);
t9 = q4+t4;
t10 = q2+t4;
t12 = t4.*2.0;
t11 = cos(t10);
t13 = cos(t12);
et1 = m4.*1.1685e-1+m5.*1.180166666666667e-1+t2.*2.3625e-2+t3.*5.74875e-2+t7.*6.605e-2+t8.*9.125e-3+t11.*5.74875e-2+t13.*2.210416666666667e-2-m5.*cos(t9.*2.0).*9.666666666666667e-4+m4.*t2.*1.575e-2+m4.*t3.*1.14975e-1;
et2 = m5.*t2.*1.575e-2+m5.*t3.*1.14975e-1+m4.*t7.*4.96125e-2+m4.*t8.*1.825e-2+m5.*t7.*4.96125e-2+m5.*t8.*1.825e-2+m4.*t11.*1.14975e-1+m5.*t11.*1.14975e-1+m4.*t13.*6.66125e-2+m5.*t13.*6.66125e-2+m5.*sin(q3+q4).*1.26e-2+m5.*sin(q2+t9).*1.26e-2+m5.*sin(t4+t9).*1.46e-2+m5.*sin(q4).*1.46e-2+(m5.*sin(t9))./5.0e+2;
et3 = 9.000416666666667e-2;
Irow = [et1+et2+et3,0.0,0.0,0.0,m5.*cos(t9).*(-2.0e-4)];
end
