function Irow = inertia_row_3(rob,in2)
%% INERTIA_ROW_3 - Computation of the robot specific inertia matrix row for corresponding to joint 3 of 5. 
% ========================================================================= 
%    
%    Irow = inertia_row_3(rob,q) 
%    Irow = rob.inertia_row_3(q) 
%    
%  Description:: 
%    Given a full set of joint variables this function computes the 
%    inertia matrix row number 3 of 5 for PANDA_sym. 
%    
%  Input:: 
%    rob: robot object of PANDA_sym specific class 
%    q:  5-element vector of generalized 
%         coordinates 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    Irow:  [1x5] row of the robot inertia matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also coriolis.
%    
    
% Copyright (C) 1993-2023, by Peter I. Corke 
% Copyright (C) 2012-2023, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Dec-2023 16:12:35

sympref('FloatingPointOutput',true);
syms m4 m5
q3 = in2(:,3);
q4 = in2(:,4);
t2 = cos(q3);
t3 = sin(q4);
t5 = m4.*1.33225e-1;
t6 = m5.*1.353583333333333e-1;
t4 = m5.*t3.*2.92e-2;
Irow = [0.0,t2.*5.74875e-2+t4+t5+t6+m4.*t2.*1.14975e-1+m5.*t2.*1.14975e-1+m5.*sin(q3+q4).*1.26e-2+4.440833333333333e-2,t4+t5+t6+4.440833333333333e-2,(m5.*(t3.*2.19e+2+3.2e+1))./1.5e+4,0.0];
end
