function G_sym = GTilde(in1)
%GTilde
%    G_sym = GTilde(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    17-Dec-2023 18:07:44

m4 = in1(:,4);
m5 = in1(:,5);
q2 = in1(:,1);
q3 = in1(:,2);
q4 = in1(:,3);
t2 = cos(q2);
t3 = cos(q3);
t4 = cos(q4);
t5 = sin(q2);
t6 = sin(q3);
t7 = sin(q4);
t8 = t2.*t3.*1.790325;
t9 = t5.*t6.*1.790325;
t10 = m5.*t2.*t3.*t7.*3.924e-1;
t11 = m5.*t2.*t4.*t6.*3.924e-1;
t12 = m5.*t3.*t4.*t5.*3.924e-1;
t13 = m5.*t5.*t6.*t7.*3.924e-1;
t15 = m4.*t2.*t3.*3.58065;
t16 = m5.*t2.*t3.*3.58065;
t18 = m4.*t5.*t6.*3.58065;
t19 = m5.*t5.*t6.*3.58065;
t14 = -t9;
t17 = -t13;
t20 = -t18;
t21 = -t19;
G_sym = [0.0,t2.*4.635225+t8+t10+t11+t12+t14+t15+t16+t17+t20+t21+m4.*t2.*3.09015+m5.*t2.*3.09015,t8+t10+t11+t12+t14+t15+t16+t17+t20+t21,t10+t11+t12+t17,0.0];
end
